# MATRICES HOMOGENEAS


In [ ]:
import numpy as np
from sympy import*
init_printing()

Declaración de Variables simbolicas

In [ ]:
theta = symbols("theta", real=True)
phi = symbols("phi", real=True)
psi = symbols("psi", real=True)

Rotación eje x

In [ ]:
H_X = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_X

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

Rotación en el Eje Y

In [ ]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y

⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

Rotación en Eje z

In [ ]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z


⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

# COMPOSICIÓN DE MATRICES HOMOGENEAS

In [ ]:
H = H_z@H_y@H_X
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [ ]:
H = H_X@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# 1 EXPERIMENTO

Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [ ]:
P0 = np.array([1, 1, 0])

## 1. PROBANDO MATRICES ROTACIÓN 3D

Matriz de rotación 3D sobre el Eje x

In [ ]:
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

Matriz de rotación 3D sobre el Eje y

In [ ]:
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


## PROBANDO COMPOSICIÓN MATRICES HOMOGENEAS

Se convierte el punto 3D a un punto de coordenadas homogeneas

In [ ]:
P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


Composición de matrices homogeneas para x & y

In [ ]:
Hxy = H_y@H_X
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# RESOLUCIÓN DEL TALLER


## 1 EJERCICIO

In [ ]:
H = H_z@H_y@H_X
theta_val = np.pi*56/180
phi_val = np.pi*2/180
psi_val = np.pi*53/180

Hzyx = np.array(H.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx

Hzyx

array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(Hzyx, P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])


## 2 Ejercicio

Declaración de variables

In [46]:
tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)

H_y = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])
H_y

tx_val = 3
ty_val = 0
tz_val = 0
theta_val = np.pi*6/180

Jtheta = np.array(H_y.subs({theta: theta_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)
Jtheta


Jphi = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
Jphi
phi_val = np.pi*2/180

Jphi1 = np.array(Jphi.subs({phi: phi_val,})).astype(np.float64) #Se convierte phi simbolico a un valor concreto
Jphi1

Jtheta2 = Matrix([[cos(theta), 0, sin(theta), tx*cos(theta) + tz*sin(theta)], [0, 1, 0, ty], [-sin(theta), 0, cos(theta), tz*cos(theta) - tx*sin(theta)], [0, 0, 0, 1]])
Jtheta2
tx_val = 1
ty_val = 1
tz_val = 0
theta_val = np.pi*-6/180

Jtheta3 = np.array(Jtheta2.subs({theta: theta_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)
Jtheta3

H = Jtheta@Jphi1@Jtheta3
H
np.dot(H, P0_homogeneo)

array([[ 4.99084836],
       [ 1.99148567],
       [-0.24429542],
       [ 1.        ]])

## 3 EJERCICIO

In [47]:
tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)
Jpsiz = Matrix([[cos(psi), -sin(psi), 0, tx], [sin(psi), cos(psi), 0, ty], [0, 0, 1, tz], [0, 0, 0, 1] ])
Jpsiz

tx_val = 3
ty_val = 0
tz_val = 0
psi_val = np.pi*53/180

Jpsiz2 = np.array(Jpsiz.subs({psi: psi_val, tx: tx_val, ty: ty_val, tz:tz_val})).astype(np.float64)
Jpsiz2

Jthetay = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
Jthetay

theta_val = np.pi*56/180

Jthetay2 = np.array(Jthetay.subs({theta: theta_val,})).astype(np.float64) #Se convierte theta simbolico a un valor concreto
Jthetay2

Jt2 = [1, 1, 0]
Jt2 = Matrix([[1, 0, 0, Jt2[0]], [0, 1, 0, Jt2[1]], [0, 0, 1, Jt2[2]], [0, 0, 0, 1]])
Jt2

Jt3 = np.array(Jt2).astype(np.float64)
Jt3

Jtheta3 = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
Jtheta3

psi_val = np.pi*53/180

J4 = np.array(Jtheta3.subs({psi: psi_val,})).astype(np.float64)
J4

H = Jpsiz2@Jthetay2@Jt3@J4
H
np.dot(H, P0_homogeneo)

array([[ 1.35320952],
       [ 1.80332018],
       [-0.66586599],
       [ 1.        ]])

## 4 Ejercicio

In [48]:
tx = symbols("tx",  real=True)
ty = symbols("ty",  real=True)
tz = symbols("tz",  real=True)

Jthetay = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
Jthetay

theta_val = np.pi*56/180

Jthetay2 = np.array(Jthetay.subs({theta: theta_val})).astype(np.float64)
Jthetay2

Jpsiz = Matrix ([[cos(psi), -sin(psi), 0, tx], [sin(psi), cos(psi), 0, ty], [0, 0, 1, tz], [0, 0, 0, 1]])
Jpsiz

tx_val = 3
ty_val = 0
tz_val = 0
psi_val = np.pi*11/180

Jpsiz2 = np.array(Jpsiz.subs({psi: psi_val,tx:tx_val, ty:ty_val,tz:tz_val})).astype(np.float64)
Jpsiz2

Jthetay3 = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
Jthetay3
psi_val = np.pi*-3/180

Jthetay4 = np.array(Jthetay3.subs({psi: psi_val})).astype(np.float64)
Jthetay4


Jphix = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
Jphix
phi_val = np.pi*2/180

Jphi4 = np.array(Jphix.subs({phi: phi_val})).astype(np.float64)
Jphi4


Jpsiz3 = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
Jpsiz3
psi_val = np.pi*278/180

Jpsi5 = np.array(Jpsiz3.subs({psi: psi_val})).astype(np.float64)
Jpsi5

H = Jthetay2 @ Jpsiz2 @ Jthetay4 @ Jphi4 @ Jpsi5
H

np.dot(H, P0_homogeneo)




array([[ 2.34457881],
       [-0.68511092],
       [-3.52909827],
       [ 1.        ]])